name: Build and Test Cookbook App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js version 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Start the application
      run: npm start &
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "gabriela.n"

  ui_tests:
    runs-on: ubuntu-latest
    needs: build-unit-test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Use Node.js version 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'
      - name: Install the dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Start the application
        run: npm start &
      - name: Run UI tests
        run: npm run test:ui

  deploy:
      runs-on: ubuntu-latest
      needs: ui_tests
      steps:
        - name: Deploy to production
          run: |
                      curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
                      -d '{"branch": "main", "commit_hash": "${{ github.sha }}"}' \
                      https://api.render.com/v1/deploys/github/${{ secrets.RENDER_PROJECT_ID }}